services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
      - ~/.composer/cache:/tmp/cache/composer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: 'mode=develop,debug client_host=host.docker.internal client_port=9003 start_with_request=yes idekey=PHPSTORM discover_client_host=0'
