x-volumes: &volumes
  volumes:
    - ../../src:/var/www/html/src
    - ../../tests:/var/www/html/tests
    - ../../composer.json:/var/www/html/composer.json

x-php-config: &php-config
  volumes:
    - ../..:/var/www/html
  extra_hosts:
    - "host.docker.internal:host-gateway"
  ports:
    - "8080:80"
    - "9003:9003"
  environment:
    PHP_IDE_CONFIG: "serverName=hermiod"
    XDEBUG_MODE: "develop,debug"
    XDEBUG_START_WITH_REQUEST: "yes"
    XDEBUG_CLIENT_HOST: "host.docker.internal"
    XDEBUG_CLIENT_PORT: "9003"
    XDEBUG_LOG: "/tmp/xdebug.log"

x-build: &build
  context: ../..
  dockerfile: ci/docker/Dockerfile

services:
  php82:
    <<: *php-config
    build:
      <<: *build
      args:
        PHP_VERSION: 8.2

  php83:
    <<: *php-config
    build:
      <<: *build
      args:
        PHP_VERSION: 8.3

  php84:
    <<: *php-config
    build:
      <<: *build
      args:
        PHP_VERSION: 8.4

  php82-ci:
    <<: *volumes
    build:
      <<: *build
      args:
        PHP_VERSION: 8.2

  php83-ci:
    <<: *volumes
    build:
      <<: *build
      args:
        PHP_VERSION: 8.3

  php84-ci:
    <<: *volumes
    build:
      <<: *build
      args:
        PHP_VERSION: 8.4
